version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/blockon
hooks:
  Install:
    - location: scripts/load_image.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
