version: "3.7"

services:
  express:
    image: blockon_express
    container_name: blockon_express
    build:
      context: .
      dockerfile: ./compose/express/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    command: sh /start.sh
    volumes:
      - .:/app
      # 호스트에 이미 디렉터리가 존재하여 컨테이너의 디렉터리가 가려지는 것 방지
      - /app/blockon-backend/node_modules
      - /app/blockon-frontend/build

  nginx:
    image: blockon_nginx
    container_name: blockon_nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express
