version: "3.7"

services:
  express:
    container_name: express
    build:
      context: .
      dockerfile: ./compose/express/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    command: sh /start.sh
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    restart: always
