version: "3.7"

services:
  express:
    image: blockon_express
    container_name: blockon_express
    build:
      context: .
      dockerfile: ./compose/express/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    command: sh /start.sh
    volumes:
      - .:/app
      - ./blockon-backend/.env:/app/blockon-backend/.env
      - /app/blockon-backend/node_modules
      - /app/blockon-frontend/node_modules
      - /app/blockon-frontend/build

  nginx:
    image: blockon_nginx
    container_name: blockon_nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express
