version: "3.7"

services:
  express:
    image: blockon_express
    container_name: express
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    command: sh /start.sh
    restart: always

  nginx:
    image: blockon_nginx
    container_name: nginx
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
    restart: always
